import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
    learnSidebar: [
        {
            type: 'autogenerated',
            dirName: 'learn'
        }
    ],
    referenceSidebar: [
        {
            type: "autogenerated",
            dirName: "reference"
        }
    ],
};

export default sidebars;
